# Isto é um comentário.
//Isto também é um comentário.

### Isto é um separador de bloco:
GET http://localhost:3000

### Isto é um separador de bloco:
GET http://localhost:3000/

### Isto é um separador de bloco:
GET http://localhost:3000/sobre

### Isto é um separador de bloco:
GET http://localhost:3000/contato

### Isto é um separador de bloco:
GET http://localhost:3000/produtos

